In [2]:
import array
arr = array.array('i',[1,2,3,4,5,6])
print(arr)

array('i', [1, 2, 3, 4, 5, 6])


In [3]:
import math
print(math.sqrt(16))

4.0


In [7]:
import random
print(random.randint(1,10))
print(random.choice(["apple","banana","kiwi"]))

6
apple


In [9]:
# directory
import os
print(os.getcwd())
print(os.listdir())

/home/paul/projects/ai/genai/u01/1-Python Basics
['1.2-dictionary.ipynb', '1.4-packages.ipynb', '1.5-standardlibraries.ipynb', '1.3-function.ipynb', '1.1-tuples.ipynb', '1.0-basic.ipynb', 'package']


In [10]:
# file
import shutil
shutil.copyfile('source.txt','destination.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'source.txt'

In [14]:
import json
data={'name':'paul','age':30}

json_str=json.dumps(data)
json1 = json.loads(json_str) 

print(json_str)
print(type(json_str))
print(json1)
print(type(json1))

{"name": "paul", "age": 30}
<class 'str'>
{'name': 'paul', 'age': 30}
<class 'dict'>


In [15]:
# csv
import csv

with open('example.csv',mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['name','age'])
    writer.writerow(['paul',30])
    writer.writerow(['pippo',35])

with open('example.csv',mode='r') as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['name', 'age']
['paul', '30']
['pippo', '35']


In [18]:
import datetime

now=datetime.datetime.now()
print(now)

yesterday=now-datetime.timedelta(days=1)
print(yesterday)

2024-09-01 16:44:19.482544
2024-08-31 16:44:19.482544


In [20]:
import time
print(time.time())
time.sleep(2)
print(time.time())

1725201897.0082648
1725201899.008932


In [25]:
# regular expression
import re

pattern=r'\d+' #any digit from 0 to 9
text='THere are 123 5 apples 456'
match=re.search(pattern, text)
print(match.group())

333


In [27]:
# read a file
with open('example.csv','r') as file:
    content=file.read()
    print(content)

with open('example.csv','r') as file:
    for line in file:
        print(line.strip())

name,age
paul,30
pippo,35

name,age
paul,30
pippo,35


In [33]:
# write a file
with open('example.csv','w') as file: # use 'a' for append
    file.write("hello world\n")
    file.write("this is a new line.\n")
    file.seek(0)
    file.write("first line.\n")


In [32]:
# write a binary file
data = b'\x00\x01\x02\x03\x04'
with open('example.bin','wb') as file:
    file.write(data)


with open('example.bin','rb') as file:
    print(file.read())


b'\x00\x01\x02\x03\x04'


In [1]:
# file path
new_dir="package"
#os.mkdir(new_dir)
print(f"Directory '{new_dir}'")

file_name="new file.txt"
fullpath=os.path.join(new_dir,file_name)
print(fullpath)

if(os.path.exists(new_dir)):
    print("folder exists")

Directory 'package'


NameError: name 'os' is not defined

In [3]:
import random
import numpy

print(numpy.random.randn(20,3))

[[-0.7280529  -1.20665908  2.23436472]
 [-0.72033641 -0.40123715  1.51600232]
 [ 0.16082718 -0.14104417 -1.08177812]
 [-1.34817554 -0.97013363  0.59495146]
 [ 0.01426973 -0.51773685 -0.47554696]
 [ 1.10754726 -0.24570923  0.52247526]
 [-0.34370416  0.1321334   0.57335539]
 [ 0.96999331  0.9853146   0.36426829]
 [-2.5525586   1.21453214 -1.21531198]
 [ 1.00675949 -1.20765694  0.08616986]
 [-0.71500578 -0.79752306 -0.41833876]
 [ 0.96774042  0.75806445  0.82887269]
 [ 0.50964702 -1.40427659  1.19271424]
 [-0.33329603 -0.01828527  0.52722026]
 [-0.89795395  1.72027882 -0.43739647]
 [ 0.25314086 -0.22113635 -1.59225226]
 [-0.23494854 -1.05816305  0.55009212]
 [-0.12458159  0.60227905  0.43741783]
 [-0.57830897 -1.16569806  0.24843126]
 [-2.34825255 -0.63609919  1.95399569]]
