In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2024-09-13 21:16:27.181722: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-13 21:16:27.772355: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-13 21:16:27.772653: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-13 21:16:27.865790: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-13 21:16:28.066061: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-13 21:16:28.069054: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
# Define the vocabulary size
voc_size = 10000

In [4]:
# One hot representation
one_hot_repr=[one_hot(word,voc_size) for word in sent]
one_hot_repr

[[5902, 8077, 8575, 2529],
 [5902, 8077, 8575, 2853],
 [5902, 6809, 8575, 1306],
 [9967, 5181, 4100, 7243, 6233],
 [9967, 5181, 4100, 7243, 1388],
 [8756, 5902, 8179, 8575, 8761],
 [9323, 6862, 3040, 7243]]

In [5]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [8]:
# padding to have sentences of the same lenght

sent_length=8 # rounded up from the number of words in the list of sentences above
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5902 8077 8575 2529]
 [   0    0    0    0 5902 8077 8575 2853]
 [   0    0    0    0 5902 6809 8575 1306]
 [   0    0    0 9967 5181 4100 7243 6233]
 [   0    0    0 9967 5181 4100 7243 1388]
 [   0    0    0 8756 5902 8179 8575 8761]
 [   0    0    0    0 9323 6862 3040 7243]]


In [9]:
# feature representation
dim=10

In [16]:
# features are the possible classification of each word (ex. male, age, food, ...)s
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

print(f"sent_length: {sent_length}, voc_size: {voc_size}")

sent_length: 8, voc_size: 10000


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)
# each word is represented by 10 items in the array

1/1 [==============================] - 0s 71ms/step


array([[[ 0.04933679,  0.00352504,  0.04265995, -0.00057896,
          0.03647229,  0.01322773, -0.01369426,  0.03341683,
          0.03632704, -0.02339108],
        [ 0.04933679,  0.00352504,  0.04265995, -0.00057896,
          0.03647229,  0.01322773, -0.01369426,  0.03341683,
          0.03632704, -0.02339108],
        [ 0.04933679,  0.00352504,  0.04265995, -0.00057896,
          0.03647229,  0.01322773, -0.01369426,  0.03341683,
          0.03632704, -0.02339108],
        [ 0.04933679,  0.00352504,  0.04265995, -0.00057896,
          0.03647229,  0.01322773, -0.01369426,  0.03341683,
          0.03632704, -0.02339108],
        [-0.04750576,  0.02172827, -0.02922004,  0.03455141,
          0.02342845, -0.00144625, -0.00692127, -0.03872278,
         -0.02435346,  0.03033866],
        [-0.03073707,  0.02286344,  0.03730031, -0.01533101,
         -0.02043747,  0.01430011, -0.00907749, -0.00447345,
          0.02035972,  0.00047056],
        [-0.02976832, -0.01871274, -0.00634702,  0.0

In [17]:
# 8 words per sentence
# 10 features
# ->
# 8 subarray (one per word in the sentence)
# 10 is the lenght of each subarray (one per feature)
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[ 0.02640623,  0.04474883, -0.02724292,  0.04356681,  0.01628871,
         0.01288262,  0.01359994,  0.04501638, -0.01337685, -0.04392293],
       [ 0.02640623,  0.04474883, -0.02724292,  0.04356681,  0.01628871,
         0.01288262,  0.01359994,  0.04501638, -0.01337685, -0.04392293],
       [ 0.02640623,  0.04474883, -0.02724292,  0.04356681,  0.01628871,
         0.01288262,  0.01359994,  0.04501638, -0.01337685, -0.04392293],
       [ 0.02640623,  0.04474883, -0.02724292,  0.04356681,  0.01628871,
         0.01288262,  0.01359994,  0.04501638, -0.01337685, -0.04392293],
       [ 0.02893901, -0.02032731, -0.00309921, -0.04708452, -0.025536  ,
        -0.02044545,  0.0142999 ,  0.0018507 ,  0.03366418,  0.01265682],
       [-0.03737019,  0.01280436,  0.03970902, -0.02193613,  0.04111854,
         0.01026414, -0.04655458, -0.03356011, -0.00992694, -0.03056669],
       [ 0.03673179, -0.04071188, -0.00352743, -0.03266939,  0.00440998,
        -0.02892788, -0.0104926 ,  0.00580841

In [18]:
embedded_docs[0].shape

(8,)